FROM  quay.io/centos/centos:stream10

ARG VERSION=nightly

ENV PULP_GUNICORN_TIMEOUT=${PULP_GUNICORN_TIMEOUT:-90}
ENV PULP_API_WORKERS=${PULP_API_WORKERS:-2}
ENV PULP_API_WORKERS_MAX_REQUESTS=${PULP_API_WORKERS_MAX_REQUESTS:-800}
ENV PULP_API_WORKERS_MAX_REQUESTS_JITTER=${PULP_API_WORKERS_MAX_REQUESTS_JITTER:-100}
ENV PULP_CONTENT_WORKERS=${PULP_CONTENT_WORKERS:-2}
ENV PULP_LOG_LEVEL=${PULP_LOG_LEVEL:-info}

RUN groupadd --system --gid 700 pulp && \
    useradd --system \
    --uid 700 \
    --gid pulp \
    --home-dir /var/lib/pulp \
    --no-create-home \
    --shell /sbin/nologin \
    pulp

RUN dnf -y update && \
    dnf -y --nodocs --setopt install_weak_deps=False install \
    https://yum.theforeman.org/pulpcore/${VERSION}/el10/$(uname -m)/pulpcore-release.rpm && \
    dnf -y --nodocs --setopt install_weak_deps=False install \
    pulpcore \
    pulpcore-plugin\({ansible,container,deb,ostree,rpm,python,smart_proxy}\) && \
    dnf clean all

COPY --chmod=0755 assets/pulp-api /usr/bin/pulp-api
COPY --chmod=0755 assets/pulp-content /usr/bin/pulp-content
COPY --chmod=0755 assets/pulp-worker /usr/bin/pulp-worker

USER pulp:pulp
