ARG PULPCORE_VERSION=latest
FROM quay.io/centos/centos:stream10

ENV PULP_GUNICORN_TIMEOUT=${PULP_GUNICORN_TIMEOUT:-90}
ENV PULP_API_WORKERS=${PULP_API_WORKERS:-2}
ENV PULP_API_WORKERS_MAX_REQUESTS=${PULP_API_WORKERS_MAX_REQUESTS:-800}
ENV PULP_API_WORKERS_MAX_REQUESTS_JITTER=${PULP_API_WORKERS_MAX_REQUESTS_JITTER:-100}
ENV PULP_CONTENT_WORKERS=${PULP_CONTENT_WORKERS:-2}

RUN groupadd --system --gid 700 pulp && \
    useradd --system \
    --uid 700 \
    --gid pulp \
    --home-dir /var/lib/pulp \
    --no-create-home \
    --shell /sbin/nologin \
    pulp


RUN dnf install 'dnf-command(config-manager)' -y && \
    dnf config-manager --set-enabled crb && \
    dnf install -y gobject-introspection-devel cairo-gobject-devel cairo-devel gcc make cmake python3-devel python3-wheel python3-pip && \
    dnf clean all

COPY pulpcore-packaging/automation/requirements.txt .

RUN pip install -r requirements.txt

COPY --chmod=0755 assets/pulp-api /usr/bin/pulp-api
COPY --chmod=0755 assets/pulp-content /usr/bin/pulp-content
COPY --chmod=0755 assets/pulp-worker /usr/bin/pulp-worker

USER pulp:pulp
