name: Container build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  container:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: pulpcore
            project: pulp
            constraints: ""
          - container: pulp-development (latest)
            project: pulp-development
            constraints: ""
          - container: pulp-development (pinned pulpcore)
            project: pulp-development
            constraints: "pulpcore==3.105.1"
    steps:
      - uses: actions/checkout@v7
      - name: Pin constraints
        if: matrix.constraints != ''
        run: echo "${{ matrix.constraints }}" >> images/pulp-development/constraints.txt
      - name: Build ${{ matrix.container }} container
        run: PROJECT=${{ matrix.project }} make build
